hw3
cooleck/reactrepo pull request #1
Opened 2020-10-20 20:59 UTC by cooleck

2020-10-22 21:38 UTC, ValeryStatinov requested changes
так же удалить папку .idea и добавить ее в гитигнор

2020-10-22 21:38 UTC, ValeryStatinov commented on my_first_app/src/MyTodoList.js
> +                <button onClick={console.log.bind(this, 'Task ' + x['id'] + ' completed status = ' + x['completed'])} className='GetStatus'>Get status</button>
зачем тут bind и что он делает?

2020-10-22 21:38 UTC, ValeryStatinov commented on my_first_app/src/MyTodoList.js
> +                <button onClick={console.log.bind(this, 'Task ' + x['id'] + ' completed status = ' + x['completed'])} className='GetStatus'>Get status</button>
обращаться к полям объекта можно так: `x.id`, `x.completed`. выглядит лучше и короче, чем `x['id']`. если нравится, то можно оставить и так

2020-10-22 22:47 UTC, cooleck commented on my_first_app/src/MyTodoList.js
> +                <button onClick={console.log.bind(this, 'Task ' + x['id'] + ' completed status = ' + x['completed'])} className='GetStatus'>Get status</button>
Это пришлось гуглить, т.к. без bind функция не работала.

2020-10-23 09:13 UTC, ValeryStatinov commented on my_first_app/src/MyTodoList.js
> +                <button onClick={console.log.bind(this, 'Task ' + x['id'] + ' completed status = ' + x['completed'])} className='GetStatus'>Get status</button>
использование стреляных функций избавляет от необходимости в bind. лучше использовать их, чем bind, тк нет понимания что это и почему с ним работает

2020-10-29 16:07 UTC, ValeryStatinov approved these changes
все хорошо, отл(10)

2020-10-29 16:07 UTC, merged